### PR TITLE
webpack configuration for hashing static assets

### PR DESCRIPTION
**Pull request by nynevi**
I have done some experimenting with webpack, with this branch being uncomplete yet:
- all the link and script tags are removed from app, welcome and editor.html files to be later injected as bundles by webpack
- webpack now takes care of hashing assets
- the folder structure of the public folder is kind of better because you know which deps are shared with which other module (app, editor, welcome) and probably will yield less build size because of bundles being chunks (we can maybe sort of later introduce lazy loading but ngx also has it so might not be as useful)

gulp replace method along with package.json version or last commit message will be experimented on because in the end we will transition to ngx anyways, it has everything setup

### CODE REVIEW

**Comment by adrianbarwicki** [comment]
Something to think about:
Structural changes are overall right now not intented -> 65 files changes are structural. We need to work the code basis to a quality level that can be migrated to angular 7 easy. Angular7 has already this webpack mechanism and once migrated, we wll might be throwing this code away anyway. Please give it a thought.

**Comment by adrianbarwicki** [comment]
Also, for reviewing changes, it is very hard to review changes in 65 files.

**Comment by nynevi** [comment]
@adrianbarwicki my point exactly was to immediately start doing stuff that is required by migration than the migration itself. but instead you again decided to create a jira task for this and put it in time estimate so like this was completely pointless and I have said this numerous times

**Comment by nynevi** [comment]
PR deleted, along with the branch

**Pull request closed without merging**
