### PR TITLE
HC-238 / added modal editor with write and edit modes

### PR DESCRIPTION
**Pull request by nynevi**
- added edit button to story page so that author can edit
- hidden follow button from author himself
- added write button to header
- editor also works responsive (though might be hard to operate)
- upvotes and unlocks have been made responsive

### CODE REVIEW

**Comment by adrianbarwicki** [comment]
failing tests @nynevi

**Comment by adrianbarwicki** [comment]
-> merge conflicts

**Comment by nynevi** [comment]
merged this in https://github.com/honest-cash/honestcash/pull/205

**Comment by adrianbarwicki** [comment]
After multiple clicks on edit, the title in the modal disapears.

**Comment by adrianbarwicki** [comment]
Closed as stalled.

**Pull request closed without merging**
