### PR TITLE
HC-185 | HC-182 | HC-186 / made some styling changes to editor

### PR DESCRIPTION
**Pull request by nynevi**
- hidden gradient on every block
- hidden three dots on every block
- header is in the plus toolbar

### CODE REVIEW

**Comment by adrianbarwicki** [comment]
How do I delete photos and videos?

**Comment by nynevi** [comment]
> How do I delete photos and videos?

select the block using arrow keys, ctrl (cmd) + a then hit backspace

**Comment by adrianbarwicki** [comment]
> > How do I delete photos and videos?
> 
> select the block using arrow keys, ctrl (cmd) + a then hit backspace
> [codex-team/editor.js#525](https://github.com/codex-team/editor.js/issues/525)

So if I dont follow this approach is kind of impossible to delete a photo :)

**Comment by adrianbarwicki** [comment]
@nynevi -> can you restore the three dots for deleting and moving up and down the images?

**Comment by nynevi** [comment]
@adrianbarwicki reenabled three dots and positioned them to the right side of each block so no overlapping happens (on images or embed etc)

**Pull request merged**
