### PR TITLE
feat(core): changed the style and the functionality of the upvote button

### LINKED ISSUE #43: Payment not competed if done right before navigation
Consider the following scenario:

1. The user reads a post 
2. The user upvotes
3. The user clicks the logo to go back to the feed

Alternatively, for step 3:

* the user clicks back
* the user closes the window

In all those cases, it's possible to do step 3 before the payment is sent.the user is left with the wrong impression that the action was completed.

Possible solutions:
* make payment buttons animated with the animation finishing when the payment is completed;
* prevent the navigation or window from being closed (as possible) while the payment is not completed, and complete the action afterwards.

### PR DESCRIPTION
**Pull request by nynevi**
- there is now a directive for the upvote button
- the upvote button has the following states: active for loading, disabled for disabling the button
- the styling of the button can be changed with backgroundColor and textColor attributes
- the text of the button can be changed with amount, text and loadingText attributes
- there is now a prompt asking "are you sure to leave?" (message is proprietary of the browser) when upvote is in progress

Closes #43

### CODE REVIEW

**Comment by adrianbarwicki** [comment]
1. You can shift addressClicked from MainCtrl to upvote-btn as it is only used there. It is a good way also to refactor a little the MainCtrl and bind the functionality to the component directly.

2. All the styles need to be isolated to upvote-button.styles.less.

3. isUpvoting need to be refactored to be part of the upvote-btn. Its possible once once the addressClicked is refactored.

4. Remove $scope and use directly the controllerAs to set up the props on the directive.

**Comment by adrianbarwicki** [comment]
css classes should have more specifc names than "upvote" or "amount"

**Comment by nynevi** [comment]
- changed css classes to encapsulate behaviour to avoid other class conflicts
- changed the amount > text transition to text > amount transition on button hover
- removed $scope from the component and started using controllerAs syntax
- refactored MainCtrl: addressClicked function is now isolated in upvote-button controller
- isUpvoting is now isolated in upvote-button controller which makes each button in the feed uniquely controlled
- I will also abstract the uncensorable button the same way (directive) so that I can refactor the makeUncensorable from MainCtrl to its own controller
- the upvote-button no longer has the customizations that can be attributed on the directive: backgroundColor, ringBackgroundColor, textColor

**Comment by nynevi** [comment]
- reverted: changed the amount > text transition to text > amount transition on button hover
- uncensorable button is now also a directive with makeUncensorable function scoped to its controller
- follow/unfollow buttons are now also a directive with functionality in the controller
- share action buttons are also a directive with functionality in the controller
- made the uncensorable and share buttons larger (it was btn-xs before, regular now)
- further refactoring in MainCtrl

**Pull request merged**
